#!/usr/bin/env python3
"""Regenerate MEMORY.md from the filesystem, PRESERVING existing curated one-liner descriptions.
Adds missing notes, drops deleted ones, regroups by folder, sorts by last_confirmed desc.
Default = dry-run (prints summary). Pass --write to apply."""
import os, re, glob, sys, shutil
sys.path.insert(0, os.path.expanduser("~/.claude/hooks"))
import _hooklib as HL
MEM=os.environ.get("CLAUDE_MEMORY_DIR") or os.path.expanduser("~/.claude/memory")
WRITE="--write" in sys.argv
# auto section titles from folder names (override via CLAUDE_SECTION_TITLES JSON)
import json as _json
_override=_json.loads(os.environ.get("CLAUDE_SECTION_TITLES","") or "{}")
order=sorted({os.path.basename(os.path.dirname(p)) for p in glob.glob(os.path.join(MEM,"*","*.md"))})
titles={f:_override.get(f, f.lstrip("_").replace("-"," ").title()) for f in order}
mem_md=os.path.join(MEM,"MEMORY.md")
# preserve existing tails
old={}
if os.path.exists(mem_md):
    for ln in open(mem_md, errors="ignore"):
        m=re.match(r'-\s*\[\[([^\]|]+)(?:\|[^\]]+)?\]\](.*)$',ln.strip())
        if m: old[m.group(1)]=m.group(2)  # includes " — desc"
def field(p,k):
    t=open(p,errors="ignore").read()[:600]
    m=re.search(rf'^{k}:\s*(.+)$',t,re.M); return m.group(1).strip().strip('"\'') if m else ""
sections={k:[] for k in order}
for p in glob.glob(os.path.join(MEM,"*","*.md")):
    b=os.path.splitext(os.path.basename(p))[0]
    if b.startswith("_"): continue
    folder=os.path.basename(os.path.dirname(p))
    if folder not in sections: continue
    tail=old.get(b) or (f" — {field(p,'description')[:120]}" if field(p,'description') else "")
    lc=field(p,'last_confirmed') or "0000-00-00"
    sections[folder].append((lc,f"- [[{b}]]{tail}"))
out=["# MEMORY — index of Claude memory notes","",
     "Grouped by project folder; `[[wikilinks]]` are move-immune. Regenerated by `/obsidian` (regen-index.py). `MEMORY.md`,`context.md`,`_session-log.md` stay at root.",""]
total=0
for k in order:
    if not sections[k]: continue
    out.append(f"## {titles[k]}")
    for _,line in sorted(sections[k],reverse=True): out.append(line); total+=1
    out.append("")
txt="\n".join(out).rstrip()+"\n"
if WRITE:
    shutil.copy2(mem_md, mem_md + ".bak") if os.path.exists(mem_md) else None
    HL.atomic_write(mem_md, txt); print(f"WROTE MEMORY.md — {total} entries (backup: MEMORY.md.bak)")
else:
    print(f"[dry-run] would write {total} entries across {sum(1 for k in order if sections[k])} sections. Pass --write to apply.")
